### ISSUE TITLE
Reset Search Crashes Switch

### ISSUE THREAD

**Issue by jtMoneyz** [tomvita/EdiZon-SE#14]
This issue applies to the latest version 3.8.14.
After using the search function to edit memory, reset search (- button) to find new values crashes the switch.

**Comment by corbinschwartz** [comment]
I'm getting this as well, consistent atmosphere crash every time reset search is used. 

11.0.1, latest atmosphere, latest EdiZon-SE. the error code is 2168-0002 (0x4a8), which looks similar to the crash in https://github.com/tomvita/EdiZon-SE/issues/15 but with different values for PC and Backtrace - Start Address.
