### ISSUE TITLE
Error 2168-0002 (0x4a8) when choosing freeze es option

### ISSUE THREAD

**Issue by ishti10** [tomvita/EdiZon-SE#28]
After freezing a variable and then resetting search, you can press the '-' minus button to choose the option labeled "freeze es"

This causes atmosphere to crash, and I have been able to repeat this error every time.

Atmosphere version 1.3.2

Error Message
ERROR CODE:2168-0002 (0X4A8)
PROGRAM:010000000000100D
FIRMWARE: 14.1.2

Can others confirm they can reproduce this error?

**Comment by theCoderCat** [comment]
i got a slightly different error, with
Error Code: 2168-0000 (0Xa8)
Same program: 010000000000100D
On the same firmware 14.1.2

Crash right after i try to launch Edizon-SE
