### ISSUE TITLE
frozen when launching after game in atmosphere 1.4.0

### ISSUE THREAD

**Issue by johnkelvinliu** [tomvita/EdiZon-SE#29]
frozen when launching after game in atmosphere 1.4.0

**Comment by Th3Alic3** [comment]
I also cannot seem to launch the app past the WELCOME SCREEN.

Complete OS freeze when attempting to push A at the Welcome.

**Comment by Fluff663** [comment]
Same issue here

**Comment by johnkelvinliu** [comment]
use bleeze instead.
https://github.com/tomvita/Breeze-Beta
